spring:
  datasource:
    url: jdbc:h2:mem:restaurant-voting
    username: sa
    password: password
    driverClassName: org.h2.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:/db/init.sql
      data-locations: classpath:/db/populate.sql
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20

  # Jackson Serialization Issue Resolver
  jackson.visibility:
    field: any
    getter: none
    setter: none
    is-getter: none
#
#  # https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#common-application-properties-cache
#  cache:
#    cache-names: users
#    caffeine.spec: maximumSize=5000,expireAfterAccess=60s

logging:
  level:
    root: WARN
    com.oleglunko.restaurantvoting: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG

server.servlet:
  encoding:
    charset: UTF-8
    enabled: true
    force: true