spring:
  datasource:
    url: jdbc:h2:mem:restaurant-voting
    username: sa
    password: password
    driverClassName: org.h2.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:/db/init.sql
      data-locations: classpath:/db/populate.sql
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20

  jackson.visibility:
    field: any
    getter: none
    setter: none
    is-getter: none

  cache:
    caffeine.spec: maximumSize=5000,expireAfterAccess=60s

logging:
  level:
    root: WARN
    com.oleglunko.restaurantvoting: DEBUG

server.servlet:
  encoding:
    charset: UTF-8
    enabled: true
    force: true